In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("/content/dataset.csv")

In [3]:
df.sample(5)

,Glucose,BMI,Insulin,Age,Gender,Diet_Type,Exercise_Frequency,Heredity,Smoking,Alcohol,Stress_Score,Sleep_Hours,Diabetes_Status
3925,131.8,24.3,89.6,34.0,Female,Unhealthy,1-2 times/week,Yes,No,Moderate,2.0,8.0,1.0
1405,145.4,35.6,79.6,47.0,Female,Unhealthy,3-5 times/week,Yes,No,NaN,4.5,7.3,1.0
3761,119.6,22.1,86.1,37.0,Female,Moderate,3-5 times/week,No,No,NaN,6.9,4.6,1.0
47,141.4,26.7,105.3,56.0,Male,Healthy,1-2 times/week,Yes,No,NaN,6.4,7.7,1.0
3732,132.1,21.2,76.5,65.0,Male,NaN,3-5 times/week,Yes,No,NaN,4.1,NaN,1.0

In [ ]:
df.shape

(5000, 13)

In [ ]:
df.isnull().sum()

Glucose                249
BMI                    209
Insulin                256
Age                    241
Gender                 246
Diet_Type              230
Exercise_Frequency     230
Heredity               257
Smoking                252
Alcohol               2618
Stress_Score           252
Sleep_Hours            242
Diabetes_Status        240
dtype: int64

In [ ]:
df.describe()

,Glucose,BMI,Insulin,Age,Stress_Score,Sleep_Hours,Diabetes_Status
count,4751.000000,4791.000000,4744.000000,4759.000000,4748.000000,4758.000000,4760.000000
mean,122.097558,26.621791,80.810835,44.285984,5.949284,6.481084,0.924580
std,32.301067,5.478449,18.897666,11.905504,1.954350,1.222833,0.264096
min,60.000000,14.000000,17.400000,18.000000,1.000000,3.000000,0.000000
25%,99.400000,22.900000,67.300000,36.000000,4.600000,5.600000,1.000000
50%,120.700000,26.500000,80.300000,44.000000,5.950000,6.500000,1.000000
75%,143.750000,30.300000,93.325000,52.000000,7.400000,7.300000,1.000000
max,238.000000,47.500000,153.700000,80.000000,10.000000,10.000000,1.000000

,Glucose,BMI,Insulin,Age,Stress_Score,Sleep_Hours,Diabetes_Status
count,4751.000000,4791.000000,4744.000000,4759.000000,4748.000000,4758.000000,4760.000000
mean,122.097558,26.621791,80.810835,44.285984,5.949284,6.481084,0.924580
std,32.301067,5.478449,18.897666,11.905504,1.954350,1.222833,0.264096
min,60.000000,14.000000,17.400000,18.000000,1.000000,3.000000,0.000000
25%,99.400000,22.900000,67.300000,36.000000,4.600000,5.600000,1.000000
50%,120.700000,26.500000,80.300000,44.000000,5.950000,6.500000,1.000000
75%,143.750000,30.300000,93.325000,52.000000,7.400000,7.300000,1.000000
max,238.000000,47.500000,153.700000,80.000000,10.000000,10.000000,1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Glucose             4751 non-null   float64
 1   BMI                 4791 non-null   float64
 2   Insulin             4744 non-null   float64
 3   Age                 4759 non-null   float64
 4   Gender              4754 non-null   object
 5   Diet_Type           4770 non-null   object
 6   Exercise_Frequency  4770 non-null   object
 7   Heredity            4743 non-null   object
 8   Smoking             4748 non-null   object
 9   Alcohol             2382 non-null   object
 10  Stress_Score        4748 non-null   float64
 11  Sleep_Hours         4758 non-null   float64
 12  Diabetes_Status     4760 non-null   float64
dtypes: float64(7), object(6)
memory usage: 507.9+ KB

In [4]:
df["Alcohol"].mode()[0]

'Low'

In [5]:
df["Alcohol"]=df["Alcohol"].fillna(df["Alcohol"].mode()[0])

In [ ]:
df.isnull().sum()

Glucose               249
BMI                   209
Insulin               256
Age                   241
Gender                246
Diet_Type             230
Exercise_Frequency    230
Heredity              257
Smoking               252
Alcohol                 0
Stress_Score          252
Sleep_Hours           242
Diabetes_Status       240
dtype: int64

In [6]:
df['Sleep_Hours'].mean()

np.float64(6.48108448928121)

In [7]:
df['Smoking']=df['Smoking'].fillna(df['Smoking'].mode()[0])

In [8]:
df['Stress_Score']=df["Stress_Score"].fillna(df["Stress_Score"].mean())

In [9]:
df["Sleep_Hours"]=df['Sleep_Hours'].fillna(df['Sleep_Hours'].mean())

In [10]:
df['Diabetes_Status']=df['Diabetes_Status'].fillna(df['Diabetes_Status'].mode()[0])

In [11]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [12]:
df['Heredity']=df['Heredity'].fillna(df['Heredity'].mode()[0])

In [13]:
df['Exercise_Frequency']=df['Exercise_Frequency'].fillna(df['Exercise_Frequency'].mode()[0])

In [14]:
df['Diet_Type']=df['Diet_Type'].fillna(df['Diet_Type'].mode()[0])

In [15]:
df['Gender']=df['Gender'].fillna(df['Gender'].mode()[0])

In [16]:
df["Insulin"]=df["Insulin"].fillna(df["Insulin"].mean())

In [17]:
df['BMI']=df['BMI'].fillna(df['BMI'].mean())

In [18]:
df['Glucose']=df['Glucose'].fillna(df['Glucose'].mean())

In [19]:
df.isnull().sum()

Glucose               0
BMI                   0
Insulin               0
Age                   0
Gender                0
Diet_Type             0
Exercise_Frequency    0
Heredity              0
Smoking               0
Alcohol               0
Stress_Score          0
Sleep_Hours           0
Diabetes_Status       0
dtype: int64

In [20]:
df.sample(5)

,Glucose,BMI,Insulin,Age,Gender,Diet_Type,Exercise_Frequency,Heredity,Smoking,Alcohol,Stress_Score,Sleep_Hours,Diabetes_Status
473,91.1,24.0,79.1,40.000000,Female,Healthy,1-2 times/week,No,No,Low,5.5,5.8,1.0
3767,111.1,33.1,44.8,44.000000,Male,Unhealthy,3-5 times/week,Yes,No,High,5.9,8.2,1.0
2395,179.5,29.4,119.7,41.000000,Female,Moderate,Rarely,Yes,No,Low,7.1,8.4,1.0
4455,141.1,25.6,90.6,62.000000,Male,Moderate,Rarely,Yes,No,Low,7.9,6.4,1.0
4876,118.9,21.7,64.4,44.285984,Female,Moderate,3-5 times/week,Yes,Yes,Low,6.6,6.1,1.0

In [21]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df[["Glucose","BMI","Insulin","Age"]]=scaler.fit_transform(df[["Glucose","BMI","Insulin","Age"]])

In [ ]:
df

,Glucose,BMI,Insulin,Age,Gender,Diet_Type,Exercise_Frequency,Heredity,Smoking,Alcohol,Stress_Score,Sleep_Hours,Diabetes_Status
0,-6.605926e-01,0.797851,0.151539,0.578106,Male,Healthy,3-5 times/week,No,No,Low,7.5,6.5,1.0
1,-9.451344e-03,0.257025,-0.114684,0.664210,Female,Unhealthy,Daily,No,No,Moderate,6.9,6.6,1.0
2,-2.850914e-02,0.107831,-0.082086,0.578106,Male,Healthy,3-5 times/week,No,No,Low,5.4,6.8,1.0
3,-6.275045e-03,-0.712732,0.667687,0.147584,Male,Moderate,Daily,No,No,Low,4.0,6.3,0.0
4,1.086372e+00,0.000000,-0.190748,-0.196833,Male,Unhealthy,1-2 times/week,No,No,Low,6.5,5.6,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1.124487e+00,0.947044,0.586190,1.869671,Male,Unhealthy,3-5 times/week,No,No,Low,5.8,7.0,1.0
4996,4.513792e-16,-1.757086,-3.445195,2.816818,Female,Moderate,Rarely,No,No,Low,5.2,7.3,1.0
4997,-2.762604e-01,-0.004064,-0.473271,0.147584,Male,Moderate,3-5 times/week,No,Yes,Moderate,6.3,4.5,1.0
4998,-1.597601e+00,0.051884,-1.918484,1.180836,Female,Healthy,Rarely,No,No,Low,4.6,6.1,1.0
4999,1.271295e-01,-1.178962,0.368864,0.233688,Female,Moderate,Rarely,No,No,Low,5.6,7.0,1.0

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:-1],
                                                df.iloc[:,-1],
                                                test_size=0.2,
                                                random_state=0)

In [23]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(drop="first",sparse_output=False,dtype=np.int32)

newX_train=ohe.fit_transform(X_train[['Gender',"Diet_Type","Exercise_Frequency","Heredity","Smoking","Alcohol"]])
newX_test=ohe.transform(X_test[['Gender',"Diet_Type","Exercise_Frequency","Heredity","Smoking","Alcohol"]])

In [24]:
newX_test

array([[0, 1, 0, ..., 0, 1, 0],
       [0, 0, 1, ..., 1, 1, 0],
       [0, 1, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 1, 0]], dtype=int32)

In [35]:
newX_train,newX_train.shape

(array([[0, 1, 0, ..., 0, 1, 0],
        [0, 0, 1, ..., 0, 1, 0],
        [1, 0, 1, ..., 1, 1, 0],
        ...,
        [1, 0, 0, ..., 0, 1, 0],
        [1, 0, 1, ..., 0, 1, 0],
        [0, 0, 1, ..., 0, 0, 0]], dtype=int32),
 (4000, 10))

In [34]:
new_dfXt=np.hstack((X_train.drop(['Gender',"Diet_Type","Exercise_Frequency","Heredity","Smoking","Alcohol"],axis=1).values, newX_train))

In [36]:
pd.DataFrame(new_dfXt)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,-1.041748e+00,-2.353860,0.347132,-1.057876,7.6,7.800000,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,1.718455e+00,0.443516,2.091167,1.266940,3.9,8.400000,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
2,-7.844682e-01,1.002992,-0.967686,0.405897,8.9,6.481084,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
3,-1.715124e+00,-1.402752,-1.130680,0.061480,6.4,5.900000,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,4.513792e-16,-0.675434,-0.701463,0.836419,7.9,6.400000,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,7.877996e-01,2.644119,0.955643,0.492001,6.8,6.481084,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
3996,2.636405e+00,-1.216260,2.020537,-0.455146,5.6,4.100000,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3997,-1.572190e+00,0.238375,-2.271638,0.750314,5.6,5.800000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3998,1.400825e+00,0.163779,0.874146,0.061480,6.0,5.600000,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3999,-2.572026e-01,2.569522,0.000000,-0.196833,3.8,3.900000,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [39]:
new_dfXte=np.hstack((X_test.drop(['Gender',"Diet_Type","Exercise_Frequency","Heredity","Smoking","Alcohol"],axis=1).values, newX_test))

In [40]:
pd.DataFrame(new_dfXte)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,0.057251,0.574061,0.330832,-1.057876,4.100000,6.3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.514638,-0.600837,0.000000,-0.110729,10.000000,4.7,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
2,-1.009985,-0.078661,-0.636265,-0.282937,5.949284,7.3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1.108606,0.443516,1.705415,-0.713459,6.200000,6.9,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,-0.698708,-0.824627,-0.277678,1.266940,7.800000,3.7,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,-1.972404,-0.544890,-0.576501,1.094732,8.100000,6.6,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
996,0.492404,0.182428,0.569890,-0.369042,10.000000,7.3,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
997,-0.733647,-0.302451,-0.092952,1.869671,6.400000,6.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
998,0.390762,-1.141663,0.705719,-0.541250,6.100000,7.7,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
999,0.562282,0.760552,0.184138,0.405897,9.600000,5.9,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [30]:
y_train

2913    1.0
3275    1.0
775     1.0
217     1.0
1245    1.0
       ...
4931    1.0
3264    1.0
1653    1.0
2607    1.0
2732    1.0
Name: Diabetes_Status, Length: 4000, dtype: float64

In [31]:
from sklearn.linear_model import LogisticRegression

In [37]:
lr=LogisticRegression()
lr.fit(new_dfXt,y_train)

LogisticRegression()

In [41]:
y_pred=lr.predict(new_dfXte)

In [42]:
from sklearn.metrics import accuracy_score

In [44]:
Score=accuracy_score(y_test,y_pred)
print(f"Accuracy Score is:{Score}")

Accuracy Score is:0.908